version: "3.9"

services:
  db:
    image: postgres:13.4
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data/pgdata
    env_file:
      - ./backend/env/pg.env
    restart: always
  web:
    build: ./backend/
    image: serje3/image-uploader-back
    env_file:
      - ./backend/env/pg.env
      - ./backend/env/server.env
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build: ./backend/nginx/
    image: serje3/image-uploader-nginx
    volumes:
      - ./backend/rest_image_uploader/static/:/static/
      - ./backend/rest_image_uploader/media/:/django_media/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - db