# Generated by Django 3.2.7 on 2021-09-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='img_url',
        ),
    ]
