# Generated by Django 3.2.6 on 2021-08-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default='0PckM5QRA5s', max_length=8, verbose_name='Photo URL'),
        ),
    ]
