# Generated by Django 3.2.6 on 2021-08-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default='tCfldsrf', max_length=8, verbose_name='Photo URL'),
        ),
    ]
